In [2]:
from sklearn.preprocessing import LabelEncoder
items = ['가나', '다라', '마바', '사아', '자차', '가나']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[0 1 2 3 4 0]


In [3]:
print(encoder.classes_)

['가나' '다라' '마바' '사아' '자차']


In [4]:
print('복원 : 디코딩 - ', encoder.inverse_transform([0, 1, 2, 3, 4, 0]))

복원 : 디코딩 -  ['가나' '다라' '마바' '사아' '자차' '가나']


In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items = ['가나', '다라', '마바', '사아', '자차', '가나']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

one_encoder = OneHotEncoder()
labels = labels.reshape(-1, 1)
one_encoder.fit(labels)
one_labels = one_encoder.transform(labels)
print(one_labels)
print(one_labels.toarray())

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 0)	1.0
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]


In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame({'items':['가나', '다라', '마바', '사아', '가나']})
pd.get_dummies(df)

items_가나  items_다라  items_마바  items_사아
0         1         0         0         0
1         0         1         0         0
2         0         0         1         0
3         0         0         0         1
4         1         0         0         0